//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerver
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIAK> DIAK { get; set; }
        public virtual DbSet<JOG> JOG { get; set; }
        public virtual DbSet<KERDES> KERDES { get; set; }
        public virtual DbSet<SZAK> SZAK { get; set; }
        public virtual DbSet<SZAK_TANTARGYAK> SZAK_TANTARGYAK { get; set; }
        public virtual DbSet<TANAR_ADMIN> TANAR_ADMIN { get; set; }
        public virtual DbSet<TANAR_TANTARGY> TANAR_TANTARGY { get; set; }
        public virtual DbSet<TANSZEK> TANSZEK { get; set; }
        public virtual DbSet<TANTARGY> TANTARGY { get; set; }
        public virtual DbSet<VALASZOK> VALASZOK { get; set; }
    
        public virtual int GETSZAKTANTARGYAK_KURZOR(string sZAK_ID)
        {
            var sZAK_IDParameter = sZAK_ID != null ?
                new ObjectParameter("SZAK_ID", sZAK_ID) :
                new ObjectParameter("SZAK_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETSZAKTANTARGYAK_KURZOR", sZAK_IDParameter);
        }
    }
}
