//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerver
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZAK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SZAK()
        {
            this.SZAK_TANTARGYAK = new HashSet<SZAK_TANTARGYAK>();
            this.DIAK = new HashSet<DIAK>();
        }
    
        public string SZAK_ID { get; set; }
        public string SZAKNEV { get; set; }
        public Nullable<byte> TSZ_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZAK_TANTARGYAK> SZAK_TANTARGYAK { get; set; }
        public virtual TANSZEK TANSZEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAK> DIAK { get; set; }
    }
}
