//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerver
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZAK_TANTARGYAK
    {
        public string SZ_ID { get; set; }
        public short T_ID { get; set; }
        public Nullable<bool> EVFOLYAM { get; set; }
    
        public virtual SZAK SZAK { get; set; }
        public virtual TANTARGY TANTARGY { get; set; }
    }
}
