//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerver
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANAR_TANTARGY
    {
        public short TA_ID { get; set; }
        public short T_ID { get; set; }
        public int K_ID { get; set; }
        public Nullable<int> OSSZEG { get; set; }
        public Nullable<int> VALASZOK_SZAMA { get; set; }
    
        public virtual KERDES KERDES { get; set; }
        public virtual TANAR_ADMIN TANAR_ADMIN { get; set; }
        public virtual TANTARGY TANTARGY { get; set; }
    }
}
