//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szerver
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANSZEK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TANSZEK()
        {
            this.SZAK = new HashSet<SZAK>();
            this.TANAR_ADMIN = new HashSet<TANAR_ADMIN>();
        }
    
        public byte TSZ_ID { get; set; }
        public string TSZ_NEV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZAK> SZAK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TANAR_ADMIN> TANAR_ADMIN { get; set; }
    }
}
